"""
The-Tongues-Book.py
===================
Project  : The Tongues Book — a parody of "The Tongue Machine" by Ansgar Allen
Author   : Joe ApocaLips / The Mass Factory
Version  : 1.5
Date     : March 2026
License  : MIT

MIT License
-----------
Copyright (c) 2026 Joe ApocaLips / The Mass Factory

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Description
-----------
Automated pipeline for generating a 200-image book of AI-generated tongue
photographs, published via Amazon KDP. Inspired by Ansgar Allen's call for
tongues (February 2026) associated with the launch of "The Tongue Machine"
(Schism Press, March 2026). Images and captions generated by Grok (xAI).

Dependencies
------------
  pip install pillow numpy requests
  Python 3.11+ (tomllib in stdlib)

Environment
-----------
  XAI_API_KEY  : xAI API key (required for image and caption generation)

Usage
-----
  python The-Tongues-Book.py N [--mode classic|wild]   generate N images
  python The-Tongues-Book.py --reprocess               PNG -> JPG (missing only)
  python The-Tongues-Book.py --retry path.json         retry one failed image
  python The-Tongues-Book.py --captions                generate .txt captions for for_pdf/
  python The-Tongues-Book.py --pdf                     build tongues_book.tex from template
  python The-Tongues-Book.py --score                   score images via Grok vision
  python The-Tongues-Book.py --contact                 generate contact sheet HTML
  python The-Tongues-Book.py --select                  apply to_add/to_remove to for_pdf/
  python The-Tongues-Book.py --find-bad                find captions matching bad_patterns.txt
  python The-Tongues-Book.py --clean-bad               delete captions marked with - in review file
  python The-Tongues-Book.py --all-captions            dump all captions to review file

Pipeline
--------
  1. generate.bat      -> tongues/*.png + *.jpg + *.json
  2. reprocess.bat     -> reprocess PNG -> JPG if needed
  3. contact.bat       -> contact.html — visual selection (click to select/deselect)
  4. select.bat        -> apply to_add.txt / to_remove.txt -> tongues/for_pdf/
  5. captions.bat      -> tongues/for_pdf/*.txt  (+ logs/captions_<datetime>.log)
  6. find_bad.bat      -> bad_captions_review.txt (patterns from bad_patterns.txt)
  7. all_captions.bat  -> full caption review file
  8. del_bad.bat       -> delete captions marked with - , regenerate
  9. make_pdf.bat      -> tongues_book.tex -> xelatex -> tongues_book.pdf

Files
-----
  The-Tongues-Book.py          this script
  params.toml                  generation parameters (edit freely)
  tongues_book_template.tex    LaTeX template (KDP 7x10, 4 plate styles)
  captions_system_prompt.txt   system prompt for Grok caption generation (edit freely)
  bad_patterns.txt             regex patterns for bad caption detection (edit freely)
  contact_template.html        HTML template for contact sheet (edit freely)
  tongues/                     generated images (PNG + JPG + JSON)
  tongues/for_pdf/             validated images for PDF (JPG + TXT)
  tongues/for_pdf/logs/        caption generation logs

Changes
-------
  1.5 : contact sheet HTML (--contact/--select), to_add/to_remove workflow,
        Downloads/ fallback in select.bat, params enriched (new poses/expressions/
        backgrounds/devices/lighting/artifacts/piercings/props), analog/digital
        compat rule, bad_patterns.txt extended, system prompt hardened
  1.4 : score rewritten — boolean criteria, _compute_reject overrides model,
        SCORE_THRESHOLD removed, defects list in output,
        pythonic refactor (_detect_style ternary, walrus in find_bad)
  1.3 : fix reject bool bug in score, analog/digital artifact compat rule
  1.2 : bad_patterns.txt externalized, score/select pipeline, clean captions workflow
  1.1 : params externalized to params.toml, VOCAB/globals() injection,
        BASE_DIR path centralization, threaded reprocess, diversified
        backgrounds/ethnicities/genders/artifacts
"""

import sys, os, json, random, time, io, argparse, tomllib
from datetime import datetime
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from multiprocessing import cpu_count
import numpy as np
from PIL import Image, ImageEnhance
import requests

# ============================================
# CONFIG
# ============================================
API_KEY_ENV        = "XAI_API_KEY"
BASE_URL           = "https://api.x.ai/v1"
IMAGE_MODEL        = "grok-imagine-image"
BASE_DIR           = Path(__file__).parent
OUTPUT_DIR         = BASE_DIR / "tongues"
PDF_DIR            = OUTPUT_DIR / "for_pdf"
PARAMS_PATH        = BASE_DIR / "params.toml"
SYSTEM_PROMPT_PATH  = BASE_DIR / "captions_system_prompt.txt"
BAD_PATTERNS_PATH   = BASE_DIR / "bad_patterns.txt"
CAPTIONS_LOG_DIR   = PDF_DIR / "logs"
TEX_TEMPLATE_PATH  = BASE_DIR / "tongues_book_template.tex"
TEX_OUT            = BASE_DIR / "tongues_book.tex"
IMAGE_WORKERS      = min(cpu_count(), 5)   # xAI image API rate limit
REPROCESS_WORKERS  = cpu_count()
TEXT_WORKERS       = 20                    # xAI text API: 607 rpm
THREAD_START_DELAY = 0.2
RETRY_ATTEMPTS     = 3
RETRY_DELAY        = 5
TARGET_DPI         = 300
MIN_WIDTH          = 2400
CONTRAST_FACTOR    = 1.3
GAMMA              = 0.88
BW_R, BW_G, BW_B  = 0.50, 0.32, 0.18

# ============================================
# PARAMS — loaded from params.toml
# ============================================
_p = tomllib.loads(PARAMS_PATH.read_text(encoding="utf-8"))

# DIRECT LIST MAPPING
VOCAB = _v = globals()
for _key, _data in _p.items():
    _v[_key]        = _data["values"]
    _v[_key + "_w"] = _data["weights"]

# combined framings
framings_portrait = _v["framings_portrait"]
framings_tongue   = _v["framings_tongue"]
framings_deep     = _v["framings_deep"]
all_framings      = framings_portrait + framings_tongue + framings_deep
all_framings_w    = _v["framings_portrait_w"] + _v["framings_tongue_w"] + _v["framings_deep_w"]

# ============================================
# ASSERTIONS — auto from TOML
# ============================================
def _check():
    for key, data in _p.items():
        v, w = data["values"], data["weights"]
        assert len(v) == len(w), f"Mismatch {key}: {len(v)} vals vs {len(w)} weights"
    assert len(all_framings) == len(all_framings_w), "Mismatch all_framings"
_check()

def _g(key): return _v[key], _v[key + "_w"]


# ============================================
# COMPAT RULES
# ============================================
_POSES_PORTRAIT_ONLY       = {"tongue pushed into cheek", "tongue pressed against teeth",
                               "tongue touching upper lip", "tongue touching upper lip from inside"}
_SELFIE_DEVICES            = {"instax instant camera", "photo booth frame"}
_SELFIE_TYPES              = {"bathroom mirror selfie", "smartphone selfie", "polaroid instant photo"}
_DEEP_INCOMPATIBLE_DEVICES = {"VHS freeze frame", "CCTV still frame", "security camera footage"}
_MUGSHOT_TYPES             = {"mugshot / police lineup"}
_MUGSHOT_BACKGROUNDS       = {"neutral white wall", "wall with some graffiti",
                               "police lineup height chart wall"}
_BATHROOM_TYPES            = {"bathroom mirror selfie"}
_BATHROOM_BACKGROUNDS      = {"tiled bathroom wall, sink visible", "tiled bathroom wall, shower visible"}
_ANALOG_TYPES              = {"polaroid instant photo", "disposable camera snapshot"}
_DIGITAL_ARTIFACTS         = {"severe jpeg compression, blocky artifacts",
                               "low quality 240p screenshot",
                               "VHS tracking error, scan lines",
                               "accidental shot, tilted frame"}

def is_valid_combo(c, mode):
    framing, ptype, lighting, device, pose, bg = (
        c["framing"], c["photo_type"], c["lighting_style"],
        c["capture_device"], c["tongue_pose"], c["background_style"]
    )
    if pose in _POSES_PORTRAIT_ONLY and framing in (framings_tongue + framings_deep):
        return False
    if lighting == "harsh phone flash" and framing in (framings_tongue + framings_deep):
        return False
    if lighting == "golden hour / sunset glow" and ptype in {
            "halftone newspaper reproduction", "webcam capture"}:
        return False
    if framing in framings_deep and ptype in _SELFIE_TYPES:
        return False
    if device == "endoscope camera" and framing not in framings_deep:
        return False
    if device in _SELFIE_DEVICES and ptype in _SELFIE_TYPES:
        return False
    if device in _DEEP_INCOMPATIBLE_DEVICES and framing in framings_deep:
        return False
    # bathroom mirror selfie must be in bathroom bg
    if ptype in _BATHROOM_TYPES and bg not in _BATHROOM_BACKGROUNDS:
        return False
    # bathroom mirror selfie incompatible with VHS/CCTV/security
    if ptype in _BATHROOM_TYPES and device in _DEEP_INCOMPATIBLE_DEVICES:
        return False
    # mugshot: portrait only, restricted backgrounds
    if ptype in _MUGSHOT_TYPES:
        if framing in (framings_tongue + framings_deep):
            return False
        if bg not in _MUGSHOT_BACKGROUNDS:
            return False
    # strict side profile: not with tongue/deep framings
    if framing == "strict side profile" and framing in (framings_tongue + framings_deep):
        return False
    # outdoor park / urban street art: not with deep framings
    if bg in {"outdoor park, trees and sunlight", "urban street art mural"} and framing in framings_deep:
        return False
    # height chart wall: mugshot only
    if bg == "police lineup height chart wall" and ptype not in _MUGSHOT_TYPES:
        return False
    # car interior: not deep framings
    if bg == "car interior, seat belt visible" and framing in framings_deep:
        return False
    # bed/pillow: overhead angle or selfie only
    if bg == "unmade bed, pillow visible" and framing not in {
            "overhead angle, subject lying back", "selfie", "close-up portrait"}:
        return False
    # indoor party dark: not with mugshot
    if bg == "crowded indoor party, dark room" and ptype in _MUGSHOT_TYPES:
        return False
    # analog photo types: no digital artifacts
    if ptype in _ANALOG_TYPES and c.get("image_artifact", "") in _DIGITAL_ARTIFACTS:
        return False
    return True

# ============================================
# PARAM KEYS PER MODE
# ============================================
def get_param_keys(mode):
    if mode == "wild":
        pt_v = _v["photo_types_classic"] + _v["photo_types_wild"]
        pt_w = _v["photo_types_classic_w"] + _v["photo_types_wild_w"]
        cd_v = _v["capture_devices_classic"] + _v["capture_devices_wild"]
        cd_w = _v["capture_devices_classic_w"] + _v["capture_devices_wild_w"]
        li_v = _v["lighting_classic"] + _v["lighting_wild"]
        li_w = _v["lighting_classic_w"] + _v["lighting_wild_w"]
    else:
        pt_v, pt_w = _g("photo_types_classic")
        cd_v, cd_w = _g("capture_devices_classic")
        li_v, li_w = _g("lighting_classic")

    keys = [
        ("tongue_pose",              *_g("tongue_poses")),
        ("tongue_state",             *_g("tongue_states")),
        ("tongue_expression",        *_g("tongue_expressions")),
        ("framing",                  all_framings,    all_framings_w),
        ("photo_type",               pt_v,            pt_w),
        ("capture_device",           cd_v,            cd_w),
        ("lighting_style",           li_v,            li_w),
        ("background_style",         *_g("background_styles")),
        ("image_artifact",           *_g("image_artifacts")),
        ("gender",                   *_g("genders")),
        ("ethnicity",                *_g("ethnicities")),
        ("tongue_piercing_type",     *_g("tongue_piercing_types")),
        ("tongue_piercing_location", *_g("tongue_piercing_locations")),
    ]
    if mode == "wild":
        keys += [
            ("prop",             *_g("props_wild")),
            ("hand",             *_g("hand_wild")),
            ("surface",          *_g("tongue_surface_wild")),
            ("tongue_accessory", *_g("tongue_accessories_wild")),
        ]
    else:
        keys += [
            ("prop",             ["None"], [1]),
            ("hand",             ["None"], [1]),
            ("surface",          ["None"], [1]),
            ("tongue_accessory", ["None"], [1]),
        ]
    return keys

# ============================================
# BALANCED SAMPLER — random.choices
# ============================================
def balanced_sample(n, mode):
    param_keys = get_param_keys(mode)
    combos, attempts = [], 0
    while len(combos) < n and (attempts := attempts + 1) <= n * 100:
        c = {k: random.choices(v, weights=w, k=1)[0]
             for k, v, w in param_keys} | {"mode": mode}
        if is_valid_combo(c, mode):
            combos.append(c)
    if len(combos) < n:
        print(f"Warning: only {len(combos)}/{n} valid combos after {attempts} attempts")
    return combos

# ============================================
# PROMPT BUILDER
# ============================================
def build_prompt(c):
    piercing   = (f", {c['tongue_piercing_type']} piercing on {c['tongue_piercing_location']}"
                  if c["tongue_piercing_type"] != "None" else "")
    device     = f", shot on {c['capture_device']}" if c["capture_device"] != "None" else ""
    state      = f", {c['tongue_state']}" if c.get("tongue_state", "normal") != "normal" else ""
    ethnicity  = f"{c['ethnicity']} " if c.get("ethnicity", "") else ""
    detail     = next((v for v in [
        c.get("tongue_accessory","None") != "None" and c.get("tongue_accessory"),
        c.get("prop","None")    != "None" and f"{c['prop']} visible",
        c.get("hand","None")    != "None" and c["hand"],
        c.get("surface","None") != "None" and f"tongue {c['surface']}",
    ] if v), "")
    return (
        f"{c['image_artifact']}, {c['photo_type']}, {c['background_style']}, "
        f"{c['lighting_style']}{device}, "
        f"{ethnicity}{c['gender']} sticking out their tongue, {c['tongue_pose']}{state}, "
        f"{c['tongue_expression']} expression, {c['framing']}"
        f"{piercing}{', ' + detail if detail else ''}"
    )

# ============================================
# FILE NAMING
# ============================================
def make_stem(prompt):
    return f"tongue_{abs(hash(prompt)):016x}"[:19]

def get_paths(stem):
    return (OUTPUT_DIR / f"{stem}.png",
            OUTPUT_DIR / f"{stem}.jpg",
            OUTPUT_DIR / f"{stem}.json")

# ============================================
# B&W — red/orange filter
# ============================================
def process_image(raw_bytes, jpg_path):
    img = Image.open(io.BytesIO(raw_bytes)).convert("RGB")
    w, h = img.size
    min_side = min(w, h)
    if min_side < MIN_WIDTH:
        scale = MIN_WIDTH / min_side
        img = img.resize((int(w * scale), int(h * scale)), Image.LANCZOS)
    arr  = np.array(img, dtype=np.float32)
    gray = np.clip(BW_R*arr[:,:,0] + BW_G*arr[:,:,1] + BW_B*arr[:,:,2], 0, 255)
    img  = ImageEnhance.Contrast(
               Image.fromarray(gray.astype(np.uint8), "L")
           ).enhance(CONTRAST_FACTOR)
    img  = img.point([int((i/255.0)**GAMMA * 255) for i in range(256)])
    img.save(jpg_path, "JPEG", dpi=(TARGET_DPI, TARGET_DPI), quality=85)

# ============================================
# REPROCESS
# ============================================
def _reprocess_one(png):
    try:
        process_image(png.read_bytes(), png.with_suffix(".jpg"))
        return True, png.name
    except Exception as e:
        return False, f"{png.name}: {e}"

def reprocess_missing():
    if not (todo := [p for p in sorted(OUTPUT_DIR.glob("tongue_*.png"))
                     if not p.with_suffix(".jpg").exists()]):
        print("Nothing to reprocess."); return
    print(f"Reprocessing {len(todo)} PNG(s) [{REPROCESS_WORKERS} workers]...")
    ok = fail = 0
    with ThreadPoolExecutor(max_workers=REPROCESS_WORKERS) as ex:
        for success, msg in ex.map(_reprocess_one, todo):
            print(f"{'OK ' if success else 'ERR'} {msg}")
            if success: ok += 1
            else:       fail += 1
    print(f"Done: {ok} OK, {fail} failed")

# ============================================
# SINGLE IMAGE PIPELINE
# ============================================
def generate_one(combo, api_key, thread_idx, forced_stem=None):
    time.sleep(thread_idx * THREAD_START_DELAY)
    prompt = build_prompt(combo)
    stem   = forced_stem or make_stem(prompt)
    if forced_stem and (OUTPUT_DIR / f"{stem}.png").exists():
        stem = make_stem(prompt + str(random.random()))
    raw_path, jpg_path, json_path = get_paths(stem)

    for attempt in range(1, RETRY_ATTEMPTS + 1):
        try:
            resp = requests.post(
                f"{BASE_URL}/images/generations",
                headers={"Authorization": f"Bearer {api_key}",
                         "Content-Type": "application/json"},
                json={"model": IMAGE_MODEL, "prompt": prompt,
                      "n": 1, "response_format": "url"},
                timeout=120,
            )
            resp.raise_for_status()
            if not (img_r := requests.get(resp.json()["data"][0]["url"], timeout=60)).ok:
                img_r.raise_for_status()
            raw_path.write_bytes(raw_bytes := img_r.content)
            process_image(raw_bytes, jpg_path)
            json_path.write_text(
                json.dumps(dict(combo) | {"prompt": prompt}, ensure_ascii=False, indent=2),
                encoding="utf-8"
            )
            print(f"OK  {raw_path.name}  {jpg_path.name}  {json_path.name}")
            return True
        except Exception as e:
            print(f"ERR attempt {attempt}/{RETRY_ATTEMPTS}: {e}")
            if attempt < RETRY_ATTEMPTS:
                time.sleep(RETRY_DELAY ** attempt)

    print(f"FAIL {stem}")
    return False

# ============================================
# TEXT GENERATOR
# ============================================
TEXT_MODEL     = "grok-4-1-fast-non-reasoning"
TEXT_BASE_URL  = "https://api.x.ai/v1/chat/completions"

def _load_system_prompt():
    return SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()

def _build_text_prompt(data):
    """Build a prompt from JSON params for text generation."""
    fields = [
        ("photo_type",        "photo type"),
        ("tongue_expression", "expression"),
        ("background_style",  "background"),
        ("capture_device",    "capture device"),
        ("tongue_state",      "tongue state"),
        ("prop",              "prop"),
        ("mode",              "mode"),
    ]
    skip = {"None", "normal"}
    parts = [f"{label}: {data[key]}"
             for key, label in fields
             if data.get(key, "") and data.get(key, "") not in skip]
    return "photograph parameters:\n" + "\n".join(parts)

def generate_text_one(jpg_path, api_key, system_prompt):
    """Generate a .txt caption for a jpg if not already present."""
    txt_path = jpg_path.with_suffix(".txt")
    if txt_path.exists():
        return True, jpg_path.name, "skipped"

    # JSON lives in tongues/, not for_pdf/
    json_path = jpg_path.with_suffix(".json")
    if not json_path.exists():
        json_path = OUTPUT_DIR / (jpg_path.stem + ".json")
    if not json_path.exists():
        return False, jpg_path.name, "no JSON found"

    try:
        data   = json.loads(json_path.read_text(encoding="utf-8"))
        prompt = _build_text_prompt(data)

        resp = requests.post(
            TEXT_BASE_URL,
            headers={"Authorization": f"Bearer {api_key}",
                     "Content-Type": "application/json"},
            json={
                "model": TEXT_MODEL,
                "messages": [
                    {"role": "system", "content": system_prompt},
                    {"role": "user",   "content": prompt},
                ],
                "max_tokens": 60,
                "temperature": 0.85,
                "top_p": 0.92,
            },
            timeout=30,
        )
        resp.raise_for_status()
        text = resp.json()["choices"][0]["message"]["content"].strip()
        txt_path.write_text(text, encoding="utf-8")
        return True, jpg_path.name, text

    except Exception as e:
        return False, jpg_path.name, str(e)

def generate_texts():
    api_key       = os.environ.get(API_KEY_ENV) or sys.exit(f"Error: {API_KEY_ENV} not set")
    system_prompt = _load_system_prompt()
    jpgs          = sorted(PDF_DIR.glob("*.jpg"))
    todo          = [j for j in jpgs if not j.with_suffix(".txt").exists()]
    if not todo:
        print("All captions already generated."); return

    print(f"Generating captions for {len(todo)}/{len(jpgs)} images  "
          f"[model: {TEXT_MODEL}, workers: {TEXT_WORKERS}]")

    CAPTIONS_LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_path = CAPTIONS_LOG_DIR / f"captions_{datetime.now().strftime('%Y%m%d_%H%M%S')}.log"
    log_lines = [
        f"captions log — {datetime.now().isoformat()}",
        f"model: {TEXT_MODEL}  workers: {TEXT_WORKERS}",
        f"prompt: {SYSTEM_PROMPT_PATH}",
        "-" * 60,
    ]

    success = failed = skipped = 0
    with ThreadPoolExecutor(max_workers=TEXT_WORKERS) as ex:
        futures = {ex.submit(generate_text_one, j, api_key, system_prompt): j for j in todo}
        for f in as_completed(futures):
            ok, name, info = f.result()
            if info == "skipped":
                skipped += 1
            elif ok:
                success += 1
                line = f"OK   {name}  |  {info}"
                print(line)
                log_lines.append(line)
            else:
                failed += 1
                line = f"ERR  {name}  |  {info}"
                print(line)
                log_lines.append(line)

    summary = f"\nDone: {success} generated, {skipped} skipped, {failed} failed"
    print(summary)
    log_lines.append("-" * 60)
    log_lines.append(summary)
    log_path.write_text("\n".join(log_lines), encoding="utf-8")
    print(f"Log: {log_path}")


# ============================================
# SCORE — experimental, undocumented
# ============================================
SCORE_MODEL   = TEXT_MODEL
SCORE_WORKERS = 10
SCORE_PROMPT  = """Analyze this AI-generated photograph of a human tongue.
Respond ONLY with valid JSON, no markdown, no explanation:
{
  "tongue_visible": true/false,
  "tongue_oversized": true/false,
  "face_human": true/false,
  "skin_natural": true/false,
  "mouth_anatomy_ok": true/false,
  "teeth_normal": true/false,
  "background_coherent": true/false,
  "lighting_coherent": true/false,
  "defects": ["list any visible defects here"]
}
Be critical and honest. Most AI images have at least some defects.
tongue_oversized=true if tongue fills more than 40% of the face area.
face_human=false if face looks plastic, mannequin-like or AI-smooth.
skin_natural=false if skin has no texture, pores, or looks waxy."""

def _compute_reject(data):
    """Compute reject from boolean criteria — don't trust model's own reject field."""
    return (
        not data.get("tongue_visible", False) or
        data.get("tongue_oversized", False) or
        not data.get("face_human", True) or
        not data.get("mouth_anatomy_ok", True)
    )

def _resize_png_b64(png_path, max_px=512):
    img = Image.open(png_path).convert("RGB")
    w, h = img.size
    if max(w, h) > max_px:
        scale = max_px / max(w, h)
        img = img.resize((int(w * scale), int(h * scale)), Image.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=85)
    import base64
    return base64.b64encode(buf.getvalue()).decode()

def score_one(png_path, api_key):
    score_path = png_path.with_suffix(".score.json")
    if score_path.exists():
        return True, png_path.name, "skipped"
    try:
        b64  = _resize_png_b64(png_path)
        resp = requests.post(
            TEXT_BASE_URL,
            headers={"Authorization": f"Bearer {api_key}",
                     "Content-Type": "application/json"},
            json={
                "model": SCORE_MODEL,
                "messages": [{"role": "user", "content": [
                    {"type": "image_url",
                     "image_url": {"url": f"data:image/jpeg;base64,{b64}"}},
                    {"type": "text", "text": SCORE_PROMPT},
                ]}],
                "max_tokens": 200,
                "temperature": 0.1,
            },
            timeout=30,
        )
        resp.raise_for_status()
        data         = json.loads(resp.json()["choices"][0]["message"]["content"].strip())
        data["png"]  = png_path.name
        data["reject"] = _compute_reject(data)  # override model's judgment
        score_path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        defects = ", ".join(data.get("defects", [])) or "none"
        return True, png_path.name, f"reject={data['reject']}  defects=[{defects}]"
    except Exception as e:
        return False, png_path.name, str(e)

def score_and_select():
    api_key = os.environ.get(API_KEY_ENV) or sys.exit(f"Error: {API_KEY_ENV} not set")
    pngs    = sorted(OUTPUT_DIR.glob("tongue_*.png"))
    todo    = [p for p in pngs if not p.with_suffix(".score.json").exists()]

    if todo:
        print(f"Scoring {len(todo)}/{len(pngs)} images [{SCORE_MODEL}, {SCORE_WORKERS} workers]...")
        ok = fail = skip = 0
        with ThreadPoolExecutor(max_workers=SCORE_WORKERS) as ex:
            futures = {ex.submit(score_one, p, api_key): p for p in todo}
            for f in as_completed(futures):
                success, name, info = f.result()
                if info == "skipped": skip += 1
                elif success:
                    ok += 1
                    print(f"OK  {name}  {info}")
                else:
                    fail += 1
                    print(f"ERR {name}  {info}")
        print(f"Scored: {ok} OK, {skip} skipped, {fail} failed\n")

    # select and copy to for_pdf/
    PDF_DIR.mkdir(parents=True, exist_ok=True)
    all_scores = sorted(OUTPUT_DIR.glob("tongue_*.score.json"))
    copied = rejected = 0
    for sf in all_scores:
        try:
            data    = json.loads(sf.read_text(encoding="utf-8"))
            reject  = data.get("reject") is True
            jpg_src = sf.with_suffix(".jpg")
            jpg_dst = PDF_DIR / jpg_src.name
            if not reject and jpg_src.exists() and not jpg_dst.exists():
                import shutil
                shutil.copy2(jpg_src, jpg_dst)
                copied += 1
            else:
                rejected += 1
        except Exception as e:
            print(f"ERR reading {sf.name}: {e}")
    print(f"Selected: {copied} copied to for_pdf/, {rejected} rejected")


PLATE_BEGIN      = "%%BEGIN_PLATE%%"
PLATE_END        = "%%END_PLATE%%"
WHITE_BORDER_THR = 220   # pixel brightness threshold for white border detection
WHITE_BORDER_PX  = 20    # border band width in pixels

def _escape_tex(text):
    """Escape special LaTeX characters in caption text."""
    for char, repl in [("\\", r"\textbackslash{}"),
                        ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
                        ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                        ("}", r"\}"), ("~", r"\textasciitilde{}"),
                        ("^", r"\^{}")]:
        text = text.replace(char, repl)
    return text

def _detect_style(jpg_path):
    """Detect plate style: platedefault | plateblack | platerotated | platerotatedblack."""
    import numpy as np
    arr  = np.array(Image.open(jpg_path).convert("L"))
    h, w = arr.shape
    rotated  = w > h
    top   = arr[:WHITE_BORDER_PX, :].mean()
    left  = arr[:, :WHITE_BORDER_PX].mean()
    right = arr[:, -WHITE_BORDER_PX:].mean()
    black_bg = all(v > WHITE_BORDER_THR for v in ([top, left] if rotated else [top, left, right]))
    return ("platerotatedblack" if rotated and black_bg else
            "platerotated"      if rotated else
            "plateblack"        if black_bg else
            "platedefault")

def make_pdf():
    if not TEX_TEMPLATE_PATH.exists():
        print(f"ERROR: template not found: {TEX_TEMPLATE_PATH}"); return
    jpgs = sorted(PDF_DIR.glob("*.jpg"))
    if not jpgs:
        print(f"No JPG found in {PDF_DIR}"); return

    template = TEX_TEMPLATE_PATH.read_text(encoding="utf-8")
    i_begin  = template.find(PLATE_BEGIN)
    i_end    = template.find(PLATE_END)
    if i_begin == -1 or i_end == -1:
        print(f"ERROR: {PLATE_BEGIN} / {PLATE_END} markers not found in template"); return

    plate_tpl = template[i_begin + len(PLATE_BEGIN):i_end]

    plates = []
    txt_count = style_counts = {"platedefault":0,"plateblack":0,"platerotated":0,"platerotatedblack":0}
    for i, jpg in enumerate(jpgs, 1):
        imgpath  = jpg.resolve().as_posix()
        txt_path = jpg.with_suffix(".txt")
        caption  = _escape_tex(txt_path.read_text(encoding="utf-8").strip()) if txt_path.exists() else f"tongue \\#{i:03d}"
        if txt_path.exists(): txt_count["platedefault"] += 0  # reuse dict as txt counter below
        style    = _detect_style(jpg)
        style_counts[style] = style_counts.get(style, 0) + 1
        plates.append(
            plate_tpl
            .replace("%%STYLE%%",   style)
            .replace("%%IMGPATH%%", imgpath)
            .replace("%%CAPTION%%", caption)
        )

    block = template[i_begin:i_end + len(PLATE_END)]
    tex   = template.replace(block, "\n".join(plates))
    TEX_OUT.write_text(tex, encoding="utf-8")
    captions_found = sum(1 for j in jpgs if j.with_suffix(".txt").exists())
    print(f"Written: {TEX_OUT}  ({len(jpgs)} plates, {captions_found} captions)")
    print(f"Styles: { {k:v for k,v in style_counts.items() if v} }")

# ============================================
# CONTACT SHEET — visual selection
# ============================================
CONTACT_HTML     = BASE_DIR / "contact.html"
CONTACT_TEMPLATE = BASE_DIR / "contact_template.html"
TO_ADD_FILE      = BASE_DIR / "to_add.txt"
TO_REMOVE_FILE   = BASE_DIR / "to_remove.txt"

def make_contact():
    pngs = sorted(OUTPUT_DIR.glob("tongue_*.png"), key=lambda p: p.stat().st_mtime, reverse=True)
    if not pngs:
        print("No PNG found."); return
    if not CONTACT_TEMPLATE.exists():
        print(f"ERROR: template not found: {CONTACT_TEMPLATE}"); return
    already = {f.stem for f in PDF_DIR.glob("*.jpg")}
    # not yet selected first, already selected at end — both sorted by mtime desc
    pngs = [p for p in pngs if p.stem not in already] + \
           [p for p in pngs if p.stem in already]
    items = "\n".join(
        f'<div class="thumb{" kept" if p.stem in already else ""}" '
        f'data-stem="{p.stem}" data-kept="{str(p.stem in already).lower()}" onclick="toggle(this)">'
        f'<img src="{p.resolve().as_posix()}">'
        f'<div class="label">{p.stem[-8:]}</div></div>'
        for p in pngs
    )
    tpl = CONTACT_TEMPLATE.read_text(encoding="utf-8")
    html = (tpl
        .replace("%%ITEMS%%",  items)
        .replace("%%TOTAL%%",  str(len(pngs)))
        .replace("%%IN_PDF%%", str(len(already))))
    CONTACT_HTML.write_text(html, encoding="utf-8")
    print(f"Contact sheet: {CONTACT_HTML}  ({len(pngs)} images, {len(already)} already in for_pdf/)")

def select_from_contact():
    """Apply to_add.txt and to_remove.txt from contact sheet export."""
    import shutil
    to_add    = {l.strip() for l in TO_ADD_FILE.read_text(encoding="utf-8").splitlines()
                 if l.strip()} if TO_ADD_FILE.exists() else set()
    to_remove = {l.strip() for l in TO_REMOVE_FILE.read_text(encoding="utf-8").splitlines()
                 if l.strip()} if TO_REMOVE_FILE.exists() else set()
    PDF_DIR.mkdir(parents=True, exist_ok=True)
    added = removed = skipped = 0
    for stem in to_add:
        jpg_src = OUTPUT_DIR / f"{stem}.jpg"
        jpg_dst = PDF_DIR / f"{stem}.jpg"
        if jpg_src.exists() and not jpg_dst.exists():
            shutil.copy2(jpg_src, jpg_dst); added += 1
        else:
            skipped += 1
    for stem in to_remove:
        if (jpg_dst := PDF_DIR / f"{stem}.jpg").exists():
            jpg_dst.unlink(); removed += 1
    for f in (TO_ADD_FILE, TO_REMOVE_FILE):
        if f.exists(): f.unlink()
    print(f"Added: {added}  removed: {removed}  skipped: {skipped}")


def _load_bad_patterns():
    return [l.strip() for l in BAD_PATTERNS_PATH.read_text(encoding="utf-8").splitlines()
            if l.strip() and not l.startswith("#")]

REVIEW_FILE = PDF_DIR / "bad_captions_review.txt"

def _write_review(lines, header_note):
    header = [
        "# bad_captions_review.txt",
        f"# {header_note}",
        "# Lines starting with '-' will be DELETED. Remove '-' to keep.",
        "# Then run: del_bad_captions.bat",
        "",
    ]
    REVIEW_FILE.write_text("\n".join(header + lines), encoding="utf-8")

def find_bad():
    import re
    patterns = _load_bad_patterns()
    rx   = re.compile("|".join(patterns), re.IGNORECASE)
    txts = sorted(PDF_DIR.glob("*.txt"))
    seen = set()
    found = []
    for t in txts:
        if t.name == REVIEW_FILE.name: continue
        if not t.with_suffix(".jpg").exists(): continue
        if rx.search(text := t.read_text(encoding="utf-8")) and t.name not in seen:
            seen.add(t.name)
            found.append((t, text.strip()))
    if not found:
        print("No bad patterns found."); return
    lines = [f"- {t.name}  |  {text}" for t, text in found]
    _write_review(lines, "Suspected bad captions — remove '-' to keep")
    print(f"Found {len(found)} suspect caption(s) — opening review file...")

def all_captions():
    txts = sorted(PDF_DIR.glob("*.txt"))
    seen = set()
    lines = []
    for t in txts:
        if t.name == REVIEW_FILE.name: continue
        if not t.with_suffix(".jpg").exists(): continue  # skip orphan txt
        if t.name in seen: continue
        seen.add(t.name)
        lines.append(f"{t.name}  |  {t.read_text(encoding='utf-8').strip()}")
    if not lines:
        print("No captions found."); return
    _write_review(lines, "All captions — add '-' at start of lines to DELETE")
    print(f"{len(lines)} captions — opening review file...")

def clean_captions():
    if not REVIEW_FILE.exists():
        print("No review file found — run --find-bad or --all-captions first"); return
    lines = [l for l in REVIEW_FILE.read_text(encoding="utf-8").splitlines()
             if l.strip() and not l.startswith("#")]
    seen = set()
    deleted = 0
    for line in lines:
        if not line.startswith("-"): continue   # keep lines without -
        stem = line[1:].split("|")[0].strip()
        if not stem or stem in seen or stem == REVIEW_FILE.name: continue
        seen.add(stem)
        txt = PDF_DIR / stem
        if txt.exists():
            txt.unlink()
            print(f"DEL {stem}")
            deleted += 1
        else:
            print(f"NOT FOUND {stem}")
    if REVIEW_FILE.exists():
        REVIEW_FILE.unlink()
    print(f"\nDeleted {deleted} caption(s). Run --captions to regenerate.")

# ============================================
# MAIN
# ============================================
def main():
    parser = argparse.ArgumentParser(description="The Tongues Book")
    grp = parser.add_mutually_exclusive_group(required=True)
    grp.add_argument("n",              type=int, nargs="?")
    grp.add_argument("--reprocess",    action="store_true")
    grp.add_argument("--retry",        metavar="JSON")
    grp.add_argument("--pdf",          action="store_true")
    grp.add_argument("--captions",     action="store_true")
    grp.add_argument("--score",        action="store_true")
    grp.add_argument("--find-bad",     action="store_true")
    grp.add_argument("--clean-bad",    action="store_true")
    grp.add_argument("--all-captions", action="store_true")
    grp.add_argument("--contact",      action="store_true")
    grp.add_argument("--select",       action="store_true")
    parser.add_argument("--mode",    choices=["classic","wild"], default="classic")
    args = parser.parse_args()

    OUTPUT_DIR.mkdir(exist_ok=True)

    if args.reprocess:
        reprocess_missing(); return

    if args.pdf:
        make_pdf(); return

    if args.captions:
        generate_texts(); return

    if args.score:
        score_and_select(); return

    if args.find_bad:
        find_bad(); return

    if args.clean_bad:
        clean_captions(); return

    if args.all_captions:
        all_captions(); return

    if args.contact:
        make_contact(); return

    if args.select:
        select_from_contact(); return

    api_key = os.environ.get(API_KEY_ENV) or sys.exit(f"Error: {API_KEY_ENV} not set")

    if args.retry:
        data  = json.loads(Path(args.retry).read_text(encoding="utf-8"))
        combo = {k: v for k, v in data.items() if k != "prompt"}
        generate_one(combo, api_key, 0, forced_stem=Path(args.retry).stem)
        return

    if not args.n or args.n <= 0:
        sys.exit("N must be > 0")

    print(f"Mode: {args.mode} | Workers: {IMAGE_WORKERS}")
    print(f"Sampling {args.n} combos...")
    combos = balanced_sample(args.n, args.mode)
    print(f"{len(combos)} combos ready\n")

    success = failed = 0
    with ThreadPoolExecutor(max_workers=IMAGE_WORKERS) as ex:
        futures = {ex.submit(generate_one, c, api_key, i): c
                   for i, c in enumerate(combos)}
        for f in as_completed(futures):
            if f.result(): success += 1
            else:          failed  += 1

    print(f"\nDone: {success} success, {failed} failed")
    sys.exit(0 if failed == 0 else 1)

if __name__ == "__main__":
    main()
    